"""Shared test fixtures."""

from __future__ import annotations

import io
import os
import struct
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

os.environ.setdefault("UPLOAD_DIR", "/tmp/markmute-test-uploads")
os.environ.setdefault("REDIS_URL", "redis://127.0.0.1:6399/0")

from app.main import app  # noqa: E402


@pytest.fixture(scope="session")
def client():
    return TestClient(app)


@pytest.fixture(autouse=True)
def _clean_uploads():
    uploads = Path(os.environ["UPLOAD_DIR"])
    import shutil

    if uploads.exists():
        shutil.rmtree(uploads)
    yield


def make_png(width=4, height=4) -> bytes:
    """Minimal valid PNG with a tEXt chunk (simulates metadata)."""
    def chunk(tag: bytes, data: bytes) -> bytes:
        out = struct.pack(">I", len(data)) + tag + data
        crc = _crc32(tag + data)
        return out + struct.pack(">I", crc & 0xFFFFFFFF)

    raw = b""
    for y in range(height):
        raw += b"\x00" + b"\xff\x00\x00" * width

    import zlib

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"tEXt", b"Software\x00Generated by Claude")
        + chunk(b"IDAT", zlib.compress(raw))
        + chunk(b"IEND", b"")
    )


def _crc32(data: bytes) -> int:
    import zlib

    return zlib.crc32(data) & 0xFFFFFFFF


@pytest.fixture
def sample_png_bytes() -> bytes:
    return make_png()


@pytest.fixture
def sample_unicode_md(tmp_path: Path) -> Path:
    p = tmp_path / "sample_with_unicode.md"
    p.write_text("Hello\u200bWorld\u200e with a bidi mark", encoding="utf-8")
    return p
