"""File API tests (upload / inspect / clean / download)."""

from __future__ import annotations

import io


def test_upload_inspect_clean_roundtrip(client, sample_png_bytes):
    # upload
    res = client.post(
        "/api/v1/files/upload",
        files={"file": ("meta.png", io.BytesIO(sample_png_bytes), "image/png")},
    )
    assert res.status_code == 200
    file_id = res.json()["file_id"]

    # inspect
    res = client.post(f"/api/v1/files/inspect/{file_id}")
    assert res.status_code == 200
    detail = res.json()["detail"]
    assert detail["kind"] == "image"
    assert detail["has_ai_metadata"] is True  # "Generated by Claude" tEXt chunk

    # clean
    res = client.post(f"/api/v1/files/clean/{file_id}")
    assert res.status_code == 200
    clean = res.json()
    assert clean["success"] is True
    assert clean["cleaned_file_id"].startswith(file_id)

    # download
    res = client.get(clean["download_url"])
    assert res.status_code == 200
    assert res.content.startswith(b"\x89PNG")


def test_upload_text_md_and_inspect(client):
    content = "README with a ZWSP\u200b hidden."
    res = client.post(
        "/api/v1/files/upload",
        files={"file": ("doc.md", io.BytesIO(content.encode()), "text/markdown")},
    )
    assert res.status_code == 200
    file_id = res.json()["file_id"]

    res = client.post(f"/api/v1/files/inspect/{file_id}")
    assert res.status_code == 200
    detail = res.json()["detail"]
    assert detail["kind"] == "container"
    assert detail["format"] == "markdown"


def test_upload_unsupported_extension_rejected(client):
    res = client.post(
        "/api/v1/files/upload",
        files={"file": ("evil.exe", io.BytesIO(b"MZ\x90\x00"), "application/octet-stream")},
    )
    assert res.status_code in (415, 400)


def test_upload_content_mismatch_rejected(client, sample_png_bytes):
    # PNG bytes claiming to be .txt
    res = client.post(
        "/api/v1/files/upload",
        files={"file": ("fake.txt", io.BytesIO(sample_png_bytes), "text/plain")},
    )
    assert res.status_code == 415


def test_inspect_missing_file_404(client):
    res = client.post("/api/v1/files/inspect/nonexistent-id")
    assert res.status_code == 404


def test_clean_text_file_removes_zwsp(client):
    content = "Hello\u200bWorld"
    res = client.post(
        "/api/v1/files/upload",
        files={"file": ("x.txt", io.BytesIO(content.encode()), "text/plain")},
    )
    file_id = res.json()["file_id"]

    res = client.post(f"/api/v1/files/clean/{file_id}")
    assert res.status_code == 200
    assert res.json()["detail"]["kind"] == "text"

    res = client.get(res.json()["download_url"])
    assert res.content.decode() == "HelloWorld"
